[WIP] 1 stylistic changes
ECDAR-AAU-SW-P5/Reveaal pull request #8
Opened 2023-10-09 12:04 UTC by frederikja163

closes #1

2023-10-09 13:07 UTC, frederikja163 commented
I am aware of the build changes. Currently waiting on #7 in order to fix the pipeline after renaming the build directory.

2023-10-09 13:41 UTC, Aavild approved these changes

2023-10-09 14:02 UTC, Animal2662 commented on src/tests/save_component/composition_tests.rs
> +    fn machine2researcher_saved_refines_self() {
```suggestion
    fn machine_2_researcher_saved_refines_self() {
```

2023-10-09 14:02 UTC, Animal2662 commented on src/tests/save_component/composition_tests.rs
> +    fn half_adm2researcher_saved_refines_self() {
```suggestion
    fn half_adm_2_researcher_saved_refines_self() {
```

2023-10-09 14:02 UTC, Animal2662 commented on src/tests/save_component/composition_tests.rs
> +    fn half_adm2machine3saved_refines_self() {
```suggestion
    fn half_adm_2_machine_3_saved_refines_self() {
```

2023-10-09 14:02 UTC, Animal2662 commented on src/tests/save_component/composition_tests.rs
> +    fn half_adm2machine2saved_refines_self() {
```suggestion
    fn half_adm_2_machine_2_saved_refines_self() {
```

2023-10-09 14:02 UTC, Animal2662 commented on src/tests/save_component/composition_tests.rs
> +    fn half_adm2machine_saved_refines_self() {
```suggestion
    fn half_adm_2_machine_saved_refines_self() {
```

2023-10-09 14:02 UTC, Animal2662 commented on src/tests/save_component/composition_tests.rs
> +    fn half_adm1machine3saved_refines_self() {
```suggestion
    fn half_adm_1_machine_3_saved_refines_self() {
```

2023-10-10 12:04 UTC, sabotack requested changes
Har lavet suggestions, men synes stadig der er enkelte filer, hvor der mangler en del underscores. 🫡

2023-10-10 13:22 UTC, rasmusq reviewed
Har lavet nogle suggestions.
Mange af dem er ekstra underscores.
Nogle er for at følge standarderne lidt bedre i cargo doc

2023-10-10 13:22 UTC, rasmusq commented on src/tests/save_component/no_operation_tests.rs
> +    fn t2saved_refines_self() {
```suggestion
    fn t2_saved_refines_self() {
```

2023-10-10 13:22 UTC, rasmusq commented on src/tests/save_component/no_operation_tests.rs
> +    fn t3saved_refines_self() {
```suggestion
    fn t3_saved_refines_self() {
```

2023-10-10 13:22 UTC, rasmusq commented on src/tests/save_component/no_operation_tests.rs
> +    fn t5saved_refines_self() {
```suggestion
    fn t5_saved_refines_self() {
```

2023-10-10 13:22 UTC, rasmusq commented on src/tests/save_component/no_operation_tests.rs
> +    fn t6saved_refines_self() {
```suggestion
    fn t6_saved_refines_self() {
```

2023-10-10 13:22 UTC, rasmusq commented on src/tests/save_component/no_operation_tests.rs
> +    fn t7saved_refines_self() {
```suggestion
    fn t7_saved_refines_self() {
```

2023-10-10 13:22 UTC, rasmusq commented on src/tests/save_component/no_operation_tests.rs
> +    fn t8saved_refines_self() {
```suggestion
    fn t8_saved_refines_self() {
```

2023-10-10 13:22 UTC, rasmusq commented on src/tests/save_component/no_operation_tests.rs
> +    fn t9saved_refines_self() {
```suggestion
    fn t9_saved_refines_self() {
```

2023-10-10 13:22 UTC, rasmusq commented on src/tests/save_component/no_operation_tests.rs
> +    fn t10saved_refines_self() {
```suggestion
    fn t10_saved_refines_self() {
```

2023-10-10 13:22 UTC, rasmusq commented on src/tests/save_component/no_operation_tests.rs
> +    fn t11saved_refines_self() {
```suggestion
    fn t11_saved_refines_self() {
```

2023-10-10 13:22 UTC, rasmusq commented on src/tests/save_component/no_operation_tests.rs
> +    fn t12saved_refines_self() {
```suggestion
    fn t12_saved_refines_self() {
```

2023-10-12 08:43 UTC, rasmusq approved these changes

2023-10-12 08:48 UTC, sabotack approved these changes

2023-10-12 10:46 UTC, Aavild approved these changes

2023-10-12 13:15 UTC, williamwoldum approved these changes

2023-10-13 08:08 UTC, merged